version: "3"
volumes:
  usersdata:

services:

    mssql:
        container_name: "usuarios-api-database"
        build:
          context: ./database/
          dockerfile: Dockerfile  
        volumes:
          - usersdata:/var/opt/mssql/data
        environment:
          SA_PASSWORD: "1q2w3e4r@AB"
          ACCEPT_EULA: "Y"
        ports:
          - 1433:1433
          
    usuarios-api:
        build:
          context: ./backend/Usuarios/Usuarios
          dockerfile: Dockerfile  
        container_name: "usuarios-api"
        ports:
          - 5000:5000
        environment:
          ASPNETCORE_ENVIRONMENT: Development
        depends_on:
          - mssql

    usuarios-frontend:
        container_name: usuarios-frontend
        build:
            context: ./frontend/goiabinha-sistema-usuario
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        environment:
            - CHOKIDAR_USEPOLLING=true
        depends_on:
          - mssql
          - usuarios-api